=== mbo12/campbellNetCDF/ecohydrology.dtd
<!-- program definition -->
<!ELEMENT program (progName,tables)>

<!ELEMENT progName (#PCDATA)>
<!ELEMENT tables (table+)>

<!ELEMENT table (tableName,outputInterval,variables)>
<!ELEMENT tableName (#PCDATA)>
<!ELEMENT outputInterval (#PCDATA)>
<!ELEMENT variables (variable+)>

<!ELEMENT variable (varName,insName?,obsName?,tableColumn, varUnits,varType)>
<!ELEMENT varName (#PCDATA)>
<!ELEMENT insName (#PCDATA)>
<!ELEMENT obsName (#PCDATA)>
<!ELEMENT tableColumn (#PCDATA)>
<!ELEMENT varUnits (#PCDATA)>
<!ELEMENT varType (#PCDATA)>

=== mbo12/campbellNetCDF/sampleProgXml/licor6262test.CR8.xml
<?xml version="1.0" ?>
<!DOCTYPE program
  SYSTEM 'ecohydrology.dtd'>
<program>
  <progName>licor6262test.CR8</progName>
  <tables>
    <table>
      <outputInterval>1.0</outputInterval>
      <tableName>licor6262</tableName>
      <variables>
        <variable>
          <varName>batt_volt_Min</varName>
          <origName>batt_volt</origName>
          <tableColumn>1</tableColumn>
          <varUnits></varUnits>
          <varType>Minimum</varType>
        </variable>
        <variable>
          <varName>PTemp</varName>
          <origName>PTemp</origName>
          <tableColumn>2</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>mvco2_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>3</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>mvh2o_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>4</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>mvpress_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>5</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>mvtemp_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>6</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>co2_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>7</tableColumn>
          <varUnits>umol/mol</varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>h2o_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>8</tableColumn>
          <varUnits>mmol/mol</varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>co2conc_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>9</tableColumn>
          <varUnits>ug/g</varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>h2oconc_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>10</tableColumn>
          <varUnits>mg/g</varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>press_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>11</tableColumn>
          <varUnits>kPa</varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>temp_6262</varName>
          <origName>licor6262</origName>
          <tableColumn>12</tableColumn>
          <varUnits>degC</varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>testco2</varName>
          <origName>caltest</origName>
          <tableColumn>13</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>testh20</varName>
          <origName>caltest</origName>
          <tableColumn>14</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
      </variables>
    </table>
  </tables>
</program>

=== mbo12/campbellNetCDF/sampleProgXml/CS616Calibration.CR3.xml
<?xml version="1.0" ?>
<!DOCTYPE program
  SYSTEM 'ecohydrology.dtd'>
<program>
	<progName>CS616Calibration.CR3</progName>
	<tables>
		<table>
			<outputInterval>10.0</outputInterval>
			<tableName>CS616Cal</tableName>
			<variables>
				<variable>
					<varName>Batt_Volt</varName>
					<tableColumn>1</tableColumn>
					<varUnits>Volts</varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>VW</varName>
					<tableColumn>2</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>PA_uS</varName>
					<tableColumn>3</tableColumn>
					<varUnits>uSec</varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>VW_2</varName>
					<tableColumn>4</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>PA_uS_2</varName>
					<tableColumn>5</tableColumn>
					<varUnits>uSec</varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>VW_3</varName>
					<tableColumn>6</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>PA_uS_3</varName>
					<tableColumn>7</tableColumn>
					<varUnits>uSec</varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>VW_4</varName>
					<tableColumn>8</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>PA_uS_4</varName>
					<tableColumn>9</tableColumn>
					<varUnits>uSec</varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>VW_5</varName>
					<tableColumn>10</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
			</variables>
		</table>
		<table>
			<outputInterval>86400.0</outputInterval>
			<tableName>Table2</tableName>
			<variables/>
		</table>
	</tables>
</program>

=== mbo12/campbellNetCDF/sampleProgXml/CR3000_soilmoisutre.CR3.xml
<?xml version="1.0" ?>
<!DOCTYPE program
  SYSTEM 'ecohydrology.dtd'>
<program>
	<progName>CR3000_soilmoisutre.CR3</progName>
	<tables>
		<table>
			<outputInterval>3600.0</outputInterval>
			<tableName>Table1</tableName>
			<variables>
				<variable>
					<varName>Batt_Volt_Avg</varName>
					<tableColumn>1</tableColumn>
					<varUnits>Volts</varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>VW_Avg</varName>
					<tableColumn>2</tableColumn>
					<varUnits></varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>VW_2_Avg</varName>
					<tableColumn>3</tableColumn>
					<varUnits></varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>VW_3_Avg</varName>
					<tableColumn>4</tableColumn>
					<varUnits></varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>VW_4_Avg</varName>
					<tableColumn>5</tableColumn>
					<varUnits></varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>VW_5_Avg</varName>
					<tableColumn>6</tableColumn>
					<varUnits></varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>T108_C_Avg</varName>
					<tableColumn>7</tableColumn>
					<varUnits>Deg C</varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>T108_C_2_Avg</varName>
					<tableColumn>8</tableColumn>
					<varUnits>Deg C</varUnits>
					<varType>Average</varType>
				</variable>
				<variable>
					<varName>VW_Std</varName>
					<tableColumn>9</tableColumn>
					<varUnits></varUnits>
					<varType>StdDev</varType>
				</variable>
				<variable>
					<varName>VW_2_Std</varName>
					<tableColumn>10</tableColumn>
					<varUnits></varUnits>
					<varType>StdDev</varType>
				</variable>
				<variable>
					<varName>VW_3_Std</varName>
					<tableColumn>11</tableColumn>
					<varUnits></varUnits>
					<varType>StdDev</varType>
				</variable>
				<variable>
					<varName>VW_4_Std</varName>
					<tableColumn>12</tableColumn>
					<varUnits></varUnits>
					<varType>StdDev</varType>
				</variable>
				<variable>
					<varName>VW_5_Std</varName>
					<tableColumn>13</tableColumn>
					<varUnits></varUnits>
					<varType>StdDev</varType>
				</variable>
				<variable>
					<varName>T108_C_Std</varName>
					<tableColumn>14</tableColumn>
					<varUnits>Deg C</varUnits>
					<varType>StdDev</varType>
				</variable>
			</variables>
		</table>
		<table>
			<outputInterval>86400.0</outputInterval>
			<tableName>Table2</tableName>
			<variables/>
		</table>
	</tables>
</program>

=== mbo12/campbellNetCDF/_includes/T105.CR1.xml
<?xml version="1.0" ?>
<!DOCTYPE program
  SYSTEM 'ecohydrology.dtd'>
<program>
  <progName>T105.CR1</progName>
  <tables>
    <table>
      <outputInterval>600.0</outputInterval>
      <tableName>Temperature</tableName>
      <variables>
        <variable>
          <varName>batt_volt_Min</varName>
          <tableColumn>1</tableColumn>
          <varUnits></varUnits>
          <varType>Minimum</varType>
        </variable>
        <variable>
          <varName>SoilTemp_10cm_Avg</varName>
          <tableColumn>2</tableColumn>
          <varUnits>degC</varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>SoilTemp_20cm_Avg</varName>
          <tableColumn>3</tableColumn>
          <varUnits>degC</varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>SoilTemp_30cm_Avg</varName>
          <tableColumn>4</tableColumn>
          <varUnits>degC</varUnits>
          <varType>Average</varType>
        </variable>
      </variables>
    </table>
  </tables>
</program>

=== mbo12/campbellNetCDF/sampleProgXml/licor6262_10hzv2.cr1.xml
<?xml version="1.0" ?>
<!DOCTYPE program
  SYSTEM 'ecohydrology.dtd'>
<program>
	<progName>licor6262_10hzv2.cr1</progName>
	<tables>
		<table>
			<outputInterval>0.1</outputInterval>
			<tableName>licor6262</tableName>
			<variables>
				<variable>
					<varName>batt_volt</varName>
					<tableColumn>1</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>co2</varName>
					<tableColumn>2</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>h2o</varName>
					<tableColumn>3</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
				<variable>
					<varName>press</varName>
					<tableColumn>4</tableColumn>
					<varUnits></varUnits>
					<varType>Sample</varType>
				</variable>
			</variables>
		</table>
	</tables>
</program>

=== mbo12/campbellNetCDF/sampleProgXml/licor6262_10hzv3.cr1.xml
<?xml version="1.0" ?>
<!DOCTYPE program
  SYSTEM 'ecohydrology.dtd'>
<program>
  <progName>licor6262_10hzv3.cr1</progName>
  <tables>
    <table>
      <outputInterval>0.1</outputInterval>
      <tableName>licor6262</tableName>
      <variables>
        <variable>
          <varName>batt_volt</varName>
          <origName>batt_volt</origName>
          <tableColumn>1</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>co2</varName>
          <origName>co2</origName>
          <insName>LI-7500</insName>
          <obsName>CO2 Concentration</obsName>
          <tableColumn>2</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>h2o</varName>
          <origName>h2o</origName>
          <insName>LI-7500</insName>
          <obsName>H2O Concentration</obsName>
          <tableColumn>3</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>press</varName>
          <origName>licor6262</origName>
          <insName>LI-7500</insName>
          <obsName>Atmospheric Pressure</obsName>
          <tableColumn>4</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
        <variable>
          <varName>temp</varName>
          <origName>licor6262</origName>
          <tableColumn>5</tableColumn>
          <varUnits></varUnits>
          <varType>Sample</varType>
        </variable>
      </variables>
    </table>
    <table>
      <outputInterval>1800.0</outputInterval>
      <tableName>licor6262_AVG</tableName>
      <variables>
        <variable>
          <varName>batt_volt_Avg</varName>
          <origName>batt_volt</origName>
          <tableColumn>1</tableColumn>
          <varUnits></varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>co2_Avg</varName>
          <origName>co2</origName>
          <insName>LI-7500</insName>
          <obsName>CO2 Concentration</obsName>
          <tableColumn>2</tableColumn>
          <varUnits></varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>h2o_Avg</varName>
          <origName>h2o</origName>
          <insName>LI-7500</insName>
          <obsName>H2O Concentration</obsName>
          <tableColumn>3</tableColumn>
          <varUnits></varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>press_Avg</varName>
          <origName>licor6262</origName>
          <insName>LI-7500</insName>
          <obsName>Atmospheric Pressure</obsName>
          <tableColumn>4</tableColumn>
          <varUnits></varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>temp_Avg</varName>
          <origName>licor6262</origName>
          <tableColumn>5</tableColumn>
          <varUnits></varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>batt_volt_Std</varName>
          <origName>batt_volt</origName>
          <tableColumn>6</tableColumn>
          <varUnits></varUnits>
          <varType>StdDev</varType>
        </variable>
        <variable>
          <varName>co2_Std</varName>
          <origName>co2</origName>
          <insName>LI-7500</insName>
          <obsName>CO2 Concentration</obsName>
          <tableColumn>7</tableColumn>
          <varUnits></varUnits>
          <varType>StdDev</varType>
        </variable>
        <variable>
          <varName>h2o_Std</varName>
          <origName>h2o</origName>
          <insName>LI-7500</insName>
          <obsName>H2O Concentration</obsName>
          <tableColumn>8</tableColumn>
          <varUnits></varUnits>
          <varType>StdDev</varType>
        </variable>
        <variable>
          <varName>press_Std</varName>
          <origName>licor6262</origName>
          <insName>LI-7500</insName>
          <obsName>Atmospheric Pressure</obsName>
          <tableColumn>9</tableColumn>
          <varUnits></varUnits>
          <varType>StdDev</varType>
        </variable>
        <variable>
          <varName>temp_Std</varName>
          <origName>licor6262</origName>
          <tableColumn>10</tableColumn>
          <varUnits></varUnits>
          <varType>StdDev</varType>
        </variable>
      </variables>
    </table>
  </tables>
</program>

=== mbo12/campbellNetCDF/sampleProgXml/4lws.CR1.xml
<?xml version="1.0" ?>
<!DOCTYPE program
  SYSTEM 'ecohydrology.dtd'>
<program>
  <progName>4lws.CR1</progName>
  <tables>
    <table>
      <outputInterval>60.0</outputInterval>
      <tableName>Table1</tableName>
      <variables>
        <variable>
          <varName>BattV_Avg</varName>
          <origName>BattV</origName>
          <tableColumn>1</tableColumn>
          <varUnits>Volts</varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>LWmV_Avg</varName>
          <origName>LWmV</origName>
          <insName>LWS-L</insName>
          <obsName>Leaf Wetness Sensor Voltage</obsName>
          <tableColumn>2</tableColumn>
          <varUnits>mV</varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>LWMDry_Tot</varName>
          <origName>LWMDry</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Dry</obsName>
          <tableColumn>3</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMCon_Tot</varName>
          <origName>LWMCon</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Contaminated</obsName>
          <tableColumn>4</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMWet_Tot</varName>
          <origName>LWMWet</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Wet</obsName>
          <tableColumn>5</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWmV_2_Avg</varName>
          <origName>LWmV_2</origName>
          <insName>LWS-L</insName>
          <obsName>Leaf Wetness Sensor Voltage</obsName>
          <tableColumn>6</tableColumn>
          <varUnits>mV</varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>LWMDry_2_Tot</varName>
          <origName>LWMDry_2</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Dry</obsName>
          <tableColumn>7</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMCon_2_Tot</varName>
          <origName>LWMCon_2</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Contaminated</obsName>
          <tableColumn>8</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMWet_2_Tot</varName>
          <origName>LWMWet_2</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Wet</obsName>
          <tableColumn>9</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWmV_3_Avg</varName>
          <origName>LWmV_3</origName>
          <insName>LWS-L</insName>
          <obsName>Leaf Wetness Sensor Voltage</obsName>
          <tableColumn>10</tableColumn>
          <varUnits>mV</varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>LWMDry_3_Tot</varName>
          <origName>LWMDry_3</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Dry</obsName>
          <tableColumn>11</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMCon_3_Tot</varName>
          <origName>LWMCon_3</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Contaminated</obsName>
          <tableColumn>12</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMWet_3_Tot</varName>
          <origName>LWMWet_3</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Wet</obsName>
          <tableColumn>13</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWmV_4_Avg</varName>
          <origName>LWmV_4</origName>
          <insName>LWS-L</insName>
          <obsName>Leaf Wetness Sensor Voltage</obsName>
          <tableColumn>14</tableColumn>
          <varUnits>mV</varUnits>
          <varType>Average</varType>
        </variable>
        <variable>
          <varName>LWMDry_4_Tot</varName>
          <origName>LWMDry_4</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Dry</obsName>
          <tableColumn>15</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMCon_4_Tot</varName>
          <origName>LWMCon_4</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Contaminated</obsName>
          <tableColumn>16</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
        <variable>
          <varName>LWMWet_4_Tot</varName>
          <origName>LWMWet_4</origName>
          <insName>LWS-L</insName>
          <obsName>Time that the Leaf Wetness Sensor is Wet</obsName>
          <tableColumn>17</tableColumn>
          <varUnits>Minutes</varUnits>
          <varType>Totalize</varType>
        </variable>
      </variables>
    </table>
    <table>
      <outputInterval>86400.0</outputInterval>
      <tableName>Table2</tableName>
      <variables>
        <variable>
          <varName>BattV_Min</varName>
          <origName>BattV</origName>
          <tableColumn>1</tableColumn>
          <varUnits>Volts</varUnits>
          <varType>Minimum</varType>
        </variable>
      </variables>
    </table>
  </tables>
</program>
